# Copyright (c) 2022 Stephan Nolting
# This file is derived from neorv32-riscof and is licensed under the BSD 3-Clause License.
# See the BSD-3-Clause-LICENSE file in the project root for license details.

name: RISC-SV RISCOF Verification

on:
  push:
  workflow_dispatch:

jobs:
  risc-sv-verification:
    runs-on: ubuntu-latest

    steps:
      - name: "📂 Repository checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: "📦 Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: "📦 Install xPack RISC-V GCC 14.2.0"
        run: |
          wget -q https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/releases/download/v14.2.0-2/xpack-riscv-none-elf-gcc-14.2.0-2-linux-x64.tar.gz
          mkdir -p "$GITHUB_WORKSPACE/riscv-gcc"
          tar -xzf xpack-riscv-none-elf-gcc-14.2.0-2-linux-x64.tar.gz -C "$GITHUB_WORKSPACE/riscv-gcc"
          echo "$GITHUB_WORKSPACE/riscv-gcc/xpack-riscv-none-elf-gcc-14.2.0-2/bin" >> $GITHUB_PATH

      - name: "📦 Install Sail RISC-V model"
        run: |
          mkdir -p "$GITHUB_WORKSPACE/sail-riscv"
          if [ -f "$GITHUB_WORKSPACE/bin/sail-riscv.tar.gz" ]; then
            tar -xzf "$GITHUB_WORKSPACE/bin/sail-riscv.tar.gz" -C "$GITHUB_WORKSPACE/sail-riscv"
            echo "$GITHUB_WORKSPACE/sail-riscv" >> $GITHUB_PATH
          else
            echo "Sail RISC-V tarball not found!"
            exit 1
          fi

      - name: "📦 Install RISCOF"
        run: |
          echo "upstream RISCOF is broken! https://github.com/riscv-software-src/riscof/issues/122"
          pip3 install git+https://github.com/riscv/riscof.git@d38859f85fe407bcacddd2efcd355ada4683aee4

      - name: "📦 Install Verilator"
        uses: veryl-lang/setup-verilator@v1

      - name: "📦 Install elf2hex"
        run: |
          mkdir -p "$GITHUB_WORKSPACE/elf2hex"
          tar -xzvf "$GITHUB_WORKSPACE/bin/elf2hex-1.0.1.tar.gz" -C "$GITHUB_WORKSPACE/elf2hex" --strip-components=1
          cd "$GITHUB_WORKSPACE/elf2hex"
          ./configure
          make
          sudo make install

      - name: "🔍 Check tools"
        run: |
          python -V
          riscv-none-elf-gcc -v
          riscv_sim_RV32 -h || true
          riscof --version
          verilator --version
          elf2hex --help

      - name: "⚙️ Run verification framework"
        run: |
          chmod u+x "$GITHUB_WORKSPACE/run.sh"
          "$GITHUB_WORKSPACE/run.sh"

      - name: "📤 Archive test report"
        uses: actions/upload-artifact@v4
        with:
          name: test_report
          path: |
            riscof_work/report.html
            riscof_work/style.css
